apiVersion: v1alpha1
kind: AgentConfig
metadata:
  name: {{ hostvars[item]['cluster_name'] }}
rendezvousIP: "{{ hostvars[item]['rendezvous_ip'] }}"
hosts:
  - hostname: master0
    role: master
    interfaces:
{% for interface in hostvars[item]['interfaces'] %}
      - name: {{ interface.name }}
        macAddress: {{ interface.mac_address }}
{% endfor %}
    networkConfig:
      interfaces:
        - name: bond0
          type: bond
          state: up
          mac-address: {{ hostvars[item]['interfaces'][0]['mac_address'] }}
          ipv4:
            enabled: false
          ipv6:
            enabled: false
          link-aggregation:
            mode: 802.3ad
            options:
              miimon: "140"
            port:
              - eno1
              - eno2
        - name: br100
          type: linux-bridge
          state: up
          ipv4:
            enabled: true
            dhcp: true
            auto-dns: true
            auto-gateway: true
            auto-routes: true
          ipv6:
            enabled: false
          bridge:
            options:
              stp:
                enabled: false
            port:
              - name: bond0
    rootDeviceHints:
      deviceName: "/dev/nvme4n1"
