apiVersion: v1
baseDomain: k8s.uotest1.poc.lab.local
compute:
  - architecture: amd64 
    hyperthreading: Enabled
    name: worker
    replicas: 1
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  replicas: 1
metadata:
  name: uotest1
networking:
  clusterNetwork:
    - cidr: 10.128.0.0/14
      hostPrefix: 23
  machineNetwork:
    - cidr: 192.168.1.0/24
  networkType: OVNKubernetes 
  serviceNetwork:
    - 172.30.0.0/16
platform:
  baremetal:
    - hostname: master0
      role: master
      interfaces:
        - name: eno1np0
          macAddress: b4:45:06:f1:0d:d1
        - name: eno2np1
          macAddress: b4:45:06:f1:0d:d2
      networkConfig:
        interfaces:
          - name: bond0
            type: bond
            state: up
            mac-address: b4:45:06:f1:0d:d1
            ipv4:
              enabled: true
              address:
                - ip: 192.168.1.8
                  prefix-length: 24
              dhcp: false
            ipv6:
              enabled: false
            link-aggregation:
              mode: 802.3ad
              options:
                miimon: "150"
              port:
                - enp0s0
                - enp1s1
        dns-resolver:
          config:
            server:
              - 172.18.0.20
        routes:
          config:
            - destination: 0.0.0.0/0
              next-hop-address: 192.168.1.1
              next-hop-interface: bond0
              table-id: 254
    - hostname: worker0
      role: worker
      interfaces:
        - name: eno1np0
          macAddress: b4:45:06:f2:a4:91
        - name: eno2np1
          macAddress: b4:45:06:f2:a4:92
      networkConfig:
        interfaces:
          - name: bond0
            type: bond
            state: up
            mac-address: b4:45:06:f2:a4:91
            ipv4:
              enabled: true
              address:
                - ip: 192.168.1.9
                  prefix-length: 24
              dhcp: false
            ipv6:
              enabled: false
            link-aggregation:
              mode: 802.3ad
              options:
                miimon: "150"
              port:
                - enp0s0
                - enp1s1
        dns-resolver:
          config:
            server:
              - 172.18.0.20
        routes:
          config:
            - destination: 0.0.0.0/0
              next-hop-address: 192.168.1.1
              next-hop-interface: bond0
              table-id: 254
pullSecret: "{{ pull_secret }}" 
sshKey: "{{ ssh_pub_key }}" 
