---
# tasks file for day1
- name: Set pull-secret fact
  ansible.builtin.set_fact:
    _pull_secret: "{\"auths\": {\"{{ inventory_hostname }}:8443\": {\"auth\": \"{{('init:' + mirror_registry_init_password) | b64encode }}\", \"email\": \"\"}}}"

- name: Create pull-secret in openshift-marketplace
  kubernetes.core.k8s:
    host: "{{ hostvars[item]['_api_url'] }}"
    api_key: "{{ openshift_auth_results['results'][cluster_index]['openshift_auth']['api_key'] }}"
    validate_certs: false
    resource_definition:
      kind: Secret
      apiVersion: v1
      metadata:
        name: pull-secret
        namespace: openshift-marketplace
      data:
        .dockerconfigjson: "{{ _pull_secret | to_json | b64encode }}"
      type: kubernetes.io/dockerconfigjson

- name: Configure operator hub
  kubernetes.core.k8s:
    host: "{{ hostvars[item]['_api_url'] }}"
    api_key: "{{ openshift_auth_results['results'][cluster_index]['openshift_auth']['api_key'] }}"
    validate_certs: false
    resource_definition: "{{ lookup('template', 'operator_hub.yml') | from_yaml }}"
  failed_when: false

- name: Configure operator catalog
  kubernetes.core.k8s:
    host: "{{ hostvars[item]['_api_url'] }}"
    api_key: "{{ openshift_auth_results['results'][cluster_index]['openshift_auth']['api_key'] }}"
    validate_certs: false
    resource_definition: "{{ lookup('template', 'operator_catalog.yml') | from_yaml }}"
  failed_when: false

- name: Configure OpenShift Update Service Namespace
  kubernetes.core.k8s:
    host: "{{ hostvars[item]['_api_url'] }}"
    api_key: "{{ openshift_auth_results['results'][cluster_index]['openshift_auth']['api_key'] }}"
    validate_certs: false
    resource_definition:
      kind: Project
      apiVersion: project.openshift.io/v1
      metadata:
        name: openshift-update-service
        labels:
          kubernetes.io/metadata.name: openshift-update-service

- name: Get mirror registry CA certificate
  ansible.builtin.shell:
    cmd: |
      openssl s_client -showcerts -verify 1 \
      -connect {{ inventory_hostname }}:8443 < /dev/null 2> /dev/null \
      | awk '/BEGIN CERTIFICATE/&&++k==2,/END CERTIFICATE/'
  register: mirror_registry_certificate

- name: Set mirror registry CA cert fact
  ansible.builtin.set_fact:
    _append_updateservice_registry:
      data:
        updateservice-registry: |
          {{ mirror_registry_certificate.stdout }}

- name: Modify mirror_registry_ca template to include additionalTrustBundle
  ansible.builtin.set_fact:
      _mirror_registry_ca_configmap: "{{ lookup('template', 'mirror_registry_ca_osus.yml.j2') | from_yaml | combine(_append_updateservice_registry) }}"

- name: Configure Registry CA cert for OpenShift Update Service
  kubernetes.core.k8s:
    host: "{{ hostvars[item]['_api_url'] }}"
    api_key: "{{ openshift_auth_results['results'][cluster_index]['openshift_auth']['api_key'] }}"
    validate_certs: false
    resource_definition:
      "{{ _mirror_registry_ca_configmap }}"

- name: Set openshift-config mirror registry CA cert fact
  ansible.builtin.set_fact:
    _append_openshift_config_registry: >-
      {"data": {"{{ groups['witness'][0] }}..8443": {{ mirror_registry_certificate.stdout | to_json }} }}

- name: Modify mirror_registry_ca template to include additionalTrustBundle
  ansible.builtin.set_fact:
      _mirror_registry_ca_configmap: "{{ lookup('template', 'mirror_registry_ca.yml.j2') | from_yaml | combine(_append_openshift_config_registry) | combine(_append_updateservice_registry) }}"

- name: Configure Registry CA cert
  kubernetes.core.k8s:
    host: "{{ hostvars[item]['_api_url'] }}"
    api_key: "{{ openshift_auth_results['results'][cluster_index]['openshift_auth']['api_key'] }}"
    validate_certs: false
    resource_definition:
      "{{ _mirror_registry_ca_configmap }}"

- name: Configure Update Service route
  kubernetes.core.k8s:
    host: "{{ hostvars[item]['_api_url'] }}"
    api_key: "{{ openshift_auth_results['results'][cluster_index]['openshift_auth']['api_key'] }}"
    validate_certs: false
    resource_definition:
      "{{ lookup('template', 'cluster_version.yml.j2') }}"

- name: wait for 1 minute for the catalog to come up
  ansible.builtin.pause:
    echo: no
    prompt: "Waiting for operator catalog"
    seconds: 60

- name: Deploy Red Hat OpenShift GitOps
  ansible.builtin.import_tasks:
    file: argocd.yml
